site_name: awsctl
site_author: Suraj Narwade
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: surajincloud/awsctl
repo_url: https://github.com/surajincloud/awsctl